apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd
  labels:
    app: fluentd
    stack: efk
data:
  fluent.conf: |
    <system>
      log_level info
      suppress_repeated_stacktrace
      suppress_config_dump
    </system>

    #### sources ####
    <source>
      @type http
      port 9880
      format json
    </source>

    <source>
      @type forward
      port 24224
    </source>

    <source>
      #use default nginx main log_format
      @type tail
      tag nginx.access
      path /var/log/nginx/access.log
      pos_file /tmp/fluentd/pos/nginx/access.log.pos
      format /^(?<remote_ip>[^ ]*) - (?<remote_user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<uri>[^\"]*) +\S*)?" (?<status_code>[^ ]*) (?<response_size>[^ ]*) "(?<referer>[^\"]*)" "(?<user_agent>[^\"]*)" "(?<forwarded_for>[^\"]*)"$/
      time_format %d/%b/%Y:%H:%M:%S %z
      types status_code:integer,response_size:integer
    </source>

    <source>
      @type tail
      tag php.error
      path /var/log/php-fpm/www-error.log
      pos_file /tmp/fluentd/pos/php-fpm/php_errors.log.pos
      format multiline
      multiline_flush_interval 2s
      format_firstline /^\[[^\]]*?\]/
      format1 /^\[(?<time>[^\]]*?)\] PHP (?<level>.*):  (?<message>.*)$/
      format2 /^Stack trace:$/
      format3 /^(?<trace>.*)/
      time_format %d-%b-%Y %H:%M:%S %Z
    </source>

    #### filters ####
    <filter nginx.access>
      @type record_transformer
      enable_ruby
      <record>
        path ${URI(URI.encode(uri.strip)).path}
      </record>
    </filter>

    <filter **>
      @type record_transformer
      enable_ruby
      <record>
        hostname "#{Socket.gethostname}"
      </record>
    </filter>

    #### matches ####
    <match fluent.**>
      @type stdout
    </match>

    <match nginx.access>
      @type elasticsearch
      host "#{ENV['FLUENT_ELASTICSEARCH_HOST']}"
      port "#{ENV['FLUENT_ELASTICSEARCH_PORT']}"
      scheme "#{ENV['FLUENT_ELASTICSEARCH_SCHEME'] || 'http'}"
      user "elastic"
      password "$ELASTICSEARCH_PASSWORD"
      logstash_format true
      logstash_prefix nginx.access
      logstash_dateformat %Y.%m.%d
      type_name log
      utc_index false
      reconnect_on_error true
      flush_interval 10
      num_threads 2
    </match>

    <match application.error>
      @type elasticsearch
      host "#{ENV['FLUENT_ELASTICSEARCH_HOST']}"
      port "#{ENV['FLUENT_ELASTICSEARCH_PORT']}"
      scheme "#{ENV['FLUENT_ELASTICSEARCH_SCHEME'] || 'http'}"
      user "elastic"
      password "$ELASTICSEARCH_PASSWORD"
      logstash_format true
      logstash_prefix application.error
      logstash_dateformat %Y.%m.%d
      type_name log
      utc_index false
      reconnect_on_error true
      flush_interval 10
      num_threads 2
    </match>

    <match php.error>
      @type elasticsearch
      host "#{ENV['FLUENT_ELASTICSEARCH_HOST']}"
      port "#{ENV['FLUENT_ELASTICSEARCH_PORT']}"
      scheme "#{ENV['FLUENT_ELASTICSEARCH_SCHEME'] || 'http'}"
      user "elastic"
      password "$ELASTICSEARCH_PASSWORD"
      logstash_format true
      logstash_prefix php.error
      logstash_dateformat %Y.%m.%d
      type_name log
      utc_index false
      reconnect_on_error true
      flush_interval 10
      num_threads 2
    </match>


  # If you want to collect k8s event logs, you shoud "@include kubernetes.conf" in fluentd.conf
  # https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch
  # https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter
  # https://github.com/fabric8io/docker-fluentd-kubernetes/issues/11  > Yeah, I use this plugin to regroup multilines (with multiline_start_regexp parameter) from my JSON docker logs on kubernetes (with ES /Fluentd / Kibana associated ), an then I parse them with fluent-plugin-parser , so I can handle correctly traceback and other multilines logs in elasticsearch.
  # https://groups.google.com/forum/#!msg/fluentd/CMZf4cTPlow/GADnOFIsBQAJ
  kubernetes.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      time_format %Y-%m-%dT%H:%M:%S.%NZ
      # tag_to_kubernetes_name_regexp \.(?<pod_name>[^\._]+)_(?<namespace>[^_]+)_(?<container_name>.+)-(?<docker_id>[a-z0-9]{64})\.log$</pod>)
      tag kubernetes.*
      format json
      read_from_head true
    </source>

    <source>
      @type tail
      format /^(?<time>[^ ]* [^ ,]*)[^\[]*\[[^\]]*\]\[(?<severity>[^ \]]*) *\] (?<message>.*)$/
      time_format %Y-%m-%d %H:%M:%S
      path /var/log/salt/minion
      pos_file /var/log/fluentd-salt.pos
      tag salt
    </source>

    <source>
      @type tail
      format syslog
      path /var/log/startupscript.log
      pos_file /var/log/fluentd-startupscript.log.pos
      tag startupscript
    </source>

    <source>
      @type tail
      format /^time="(?<time>[^)]*)" level=(?<severity>[^ ]*) msg="(?<message>[^"]*)"( err="(?<error>[^"]*)")?( statusCode=($<status_code>\d+))?/
      path /var/log/docker.log
      pos_file /var/log/fluentd-docker.log.pos
      tag docker
    </source>

    <source>
      @type tail
      format none
      path /var/log/etcd.log
      pos_file /var/log/fluentd-etcd.log.pos
      tag etcd
    </source>

    <source>
      @type tail
      format kubernetes
      multiline_flush_interval 5s
      path /var/log/kubelet.log
      pos_file /var/log/fluentd-kubelet.log.pos
      tag kubelet
    </source>

    <source>
      @type tail
      format kubernetes
      multiline_flush_interval 5s
      path /var/log/kube-proxy.log
      pos_file /var/log/fluentd-kube-proxy.log.pos
      tag kube-proxy
    </source>

    <source>
      @type tail
      format kubernetes
      multiline_flush_interval 5s
      path /var/log/kube-apiserver.log
      pos_file /var/log/fluentd-kube-apiserver.log.pos
      tag kube-apiserver
    </source>

    <source>
      @type tail
      format kubernetes
      multiline_flush_interval 5s
      path /var/log/kube-controller-manager.log
      pos_file /var/log/fluentd-kube-controller-manager.log.pos
      tag kube-controller-manager
    </source>

    <source>
      @type tail
      format kubernetes
      multiline_flush_interval 5s
      path /var/log/kube-scheduler.log
      pos_file /var/log/fluentd-kube-scheduler.log.pos
      tag kube-scheduler
    </source>

    <source>
      @type tail
      format kubernetes
      multiline_flush_interval 5s
      path /var/log/rescheduler.log
      pos_file /var/log/fluentd-rescheduler.log.pos
      tag rescheduler
    </source>

    <source>
      @type tail
      format kubernetes
      multiline_flush_interval 5s
      path /var/log/glbc.log
      pos_file /var/log/fluentd-glbc.log.pos
      tag glbc
    </source>

    <source>
      @type tail
      format kubernetes
      multiline_flush_interval 5s
      path /var/log/cluster-autoscaler.log
      pos_file /var/log/fluentd-cluster-autoscaler.log.pos
      tag cluster-autoscaler
    </source>

    <filter kubernetes.**>
      @type kubernetes_metadata
    </filter>
