apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd
  labels:
    app: fluentd
    stack: efk
spec:
  template:
    metadata:
      name: fluentd
      labels:
        app: fluentd
    spec:
      serviceAccountName: fluentd
      containers:
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:v1.2-debian-elasticsearch
        imagePullPolicy: IfNotPresent
        command: ["fluentd", "-c", "/fluentd/etc/fluent.conf", "-p", "/fluentd/plugins", "--gemfile", "/fluentd/Gemfile"]
        env:
        - name:  FLUENT_ELASTICSEARCH_HOST
          value: "elasticsearch.$NAMESPACE.svc"
        - name:  FLUENT_ELASTICSEARCH_PORT
          value: "9200"
        - name: FLUENT_ELASTICSEARCH_SCHEME
          value: "http"
        - name:  FLUENT_ELASTICSEARCH_LOGSTASH_PREFIX
          value: "fluentd"
        ports:
        - name: http
          containerPort: 9880
        - name: forward
          containerPort: 24224
        resources:
          requests:
            cpu: 0.4
            memory: 200Mi
          limits:
            cpu: 0.8
            memory: 400Mi
        volumeMounts:
        - name: config
          mountPath: /fluentd/etc/fluent.conf
          subPath: fluent.conf
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
        - name: pos
          mountPath: /tmp/fluentd/pos
        securityContext:
          runAsUser: 0
      volumes:
      - name: config
        configMap:
          name: fluentd
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: pos
        hostPath:
          path: /data/efk/fluentd/pos
