apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd
  labels:
    app: fluentd
spec:
  template:
    metadata:
      name: fluentd
      labels:
        app: fluentd
    spec:
      serviceAccountName: fluentd
      containers:
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:v0.12-elasticsearch
        imagePullPolicy: IfNotPresent
        env:
        - name:  FLUENT_ELASTICSEARCH_HOST
          value: elasticsearch-efk.$NAMESPACE.svc
        - name:  FLUENT_ELASTICSEARCH_PORT
          value: 9200
        - name: FLUENT_ELASTICSEARCH_SCHEME
          value: http
        - name:  FLUENT_ELASTICSEARCH_LOGSTASH_PREFIX
          value: fluentd
        # X-Pack Authentication
        #- name: FLUENT_ELASTICSEARCH_USER
        #  value: elastic
        #- name: FLUENT_ELASTICSEARCH_PASSWORD
        #  value: changeme
        ports:
        - name: http
          containerPort: 9880
        - name: forward
          containerPort: 24224
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: config
          mountPath: /fluentd/etc
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
        securityContext:
          runAsUser: 0
      volumes:
      - name: config
        configMap:
          name: fluentd
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers