apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fluentd
  labels:
    app: fluentd
    stack: efk
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: fluentd
        stack: efk
    spec:
      restartPolicy: Always
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: efk-node
                operator: In
                values:
                - "true"
      imagePullSecrets:
      - name: myregistrykey
      containers:
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:v1.2-debian-elasticsearch
        imagePullPolicy: imagePullPolicy
        command: ["fluentd", "-c", "/fluentd/etc/fluent.conf", "-p", "/fluentd/plugins", "--gemfile", "/fluentd/Gemfile"]
        ports:
        - name: http
          containerPort: 9880
        - name: forward
          containerPort: 24224
        resources:
          requests:
            cpu: 0.4
            memory: 200Mi
          limits:
            cpu: 0.8
            memory: 500Mi
        volumeMounts:
        - name: config
          mountPath: /fluentd/etc/fluent.conf
          subPath: fluent.conf
        - name: varlog
          mountPath: /var/log
        - name: pos
          mountPath: /tmp/fluentd/pos
        securityContext:
          runAsUser: 0
      volumes:
      - name: config
        configMap:
          name: fluentd
      - name: varlog
        hostPath:
          path: /var/log
      - name: pos
        hostPath:
          path: /data/efk/fluentd/pos
