apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
    stack: logging
spec:
  rules:
  -
    host: elasticsearch.efk.yoursite.com
    http:
      paths:
      - path: /
        backend:
          serviceName: elasticsearch
          servicePort: 9200
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kibana
  labels:
    app: kibana
    stack: logging
spec:
  rules:
  -
    host: kibana.efk.yoursite.com
    http:
      paths:
      - path: /
        backend:
          serviceName: kibana
          servicePort: 5601
