apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
    stack: efk
data:
  elasticsearch.yml: |
    cluster.name: efk-cluster
    node.name: efk-node-alpha
    path:
      data: /usr/share/elasticsearch/data
      logs: /usr/share/elasticsearch/log
    bootstrap.memory_lock: true
    network.host: ${BIND_ADDRESS}
    http:
      host: ${BIND_ADDRESS}
      port: 9200
    transport:
      host: ${BIND_ADDRESS}
      tcp:
        port: 9300
    discovery.zen.minimum_master_nodes: ${MINIMUM_MASTER_NODES}
    discovery.zen.ping.unicast.hosts: ${UNICAST_HOSTS}
