apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
    stack: efk
data:
  elasticsearch.yml: |
    cluster.name: efk-cluster
    node:
      name: efk-node-alpha
      master: true
      data: true
      ingest: false
      max_local_storage_nodes: 1
    path:
      data: /usr/share/elasticsearch/data
      logs: /usr/share/elasticsearch/log
    bootstrap.memory_lock: true
    search.remote.connect: false
    network.host: ${NETWORK_HOST}
    http:
      enabled: true
      host: ${BIND_ADDRESS}
      port: 9200
    transport:
      host: ${BIND_ADDRESS}
      tcp:
        port: 9300
    discovery:
      type: single-node
      #zen:
      #  minimum_master_nodes: ${MINIMUM_MASTER_NODES}
      #  ping:
      #    unicast:
      #      hosts: ${UNICAST_HOSTS}
    xpack.security.enabled: true
    xpack.monitoring.enabled: true
    xpack.ml.enabled: false
    xpack.watcher.enabled: false
    xpack.security.audit.enabled: false
    xpack.security.http.ssl.enabled: false
    xpack.security.transport.ssl.enabled: false
  limits.conf: |
    # allow user 'elasticsearch' mlockall
    elasticsearch soft memlock unlimited
    elasticsearch hard memlock unlimited
