apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
    stack: logging
data:
  elasticsearch.yml: |
    cluster.name: efk-cluster
    node.name: efk-node-alpha
    path:
      data: /usr/share/elasticsearch/data
      logs: /usr/share/elasticsearch/log
    bootstrap.memory_lock: true
    http.port: 9200
    transport.tcp.port: 9300
    transport.host: 127.0.0.1
    network.host: ${NETWORK_HOST}
    discovery.zen.minimum_master_nodes: ${MINIMUM_MASTER_NODES}
    discovery.zen.ping.unicast.hosts: elasticsearch-efk.$NAMESPACE.svc:9300
