apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
    stack: efk
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: elasticsearch
        stack: efk
    spec:
      serviceAccountName: elasticsearch
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: efknode
                operator: In
                values:
                - "true"
      initContainers:
      - name: set-vm-max-map-count
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sysctl', '-w', 'vm.max_map_count=262144']
        securityContext:
          privileged: true
      - name: volume-mount-hack
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "chown -R 1000:100 /usr/share/elasticsearch/data /usr/share/elasticsearch/log"]
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
        - name: log
          mountPath: /usr/share/elasticsearch/log
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.0.1
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        env:
        - name: ES_JAVA_OPTS
          value: "-Xms1g -Xmx1g"
        - name: MINIMUM_MASTER_NODES
          value: "1"
        - name: BIND_ADDRESS
          value: "0.0.0.0"
        - name: UNICAST_HOSTS
          value: "elasticsearch.$NAMESPACE.svc"
        ports:
        - name: api
          containerPort: 9200
        - name: transport
          containerPort: 9300
        resources:
          requests:
            cpu: 1
            memory: 2000Mi
          limits:
            cpu: 1
            memory: 2000Mi
        volumeMounts:
        - name: config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
        - name: data
          mountPath: /usr/share/elasticsearch/data
        - name: log
          mountPath: /usr/share/elasticsearch/log
      # Allow non-root user to access PersistentVolume
      securityContext:
        fsGroup: 1000
      restartPolicy: Always
      volumes:
      - name: config
        configMap:
          name: elasticsearch
      - name: data
        hostPath:
          path: /data/efk/elasticsearch/data
      - name: log
        hostPath:
          path: /data/efk/elasticsearch/log
      #- name: datalog
      #  persistentVolumeClaim:
      #    claimName: elasticsearch

#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: elasticsearch
#  labels:
#    app: elasticsearch
#    stack: efk
#spec:
#  storageClassName: standard
#  accessModes:
#  - ReadWriteOnce
#  resources:
#    requests:
#      storage: 10G
