apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
    stack: efk
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: elasticsearch
        stack: efk
    spec:
      restartPolicy: Always
      serviceAccountName: elasticsearch
      securityContext:
        fsGroup: 1000 # Allow non-root user to access PersistentVolume
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: efk-node
                operator: In
                values:
                - "true"
      initContainers:
      - name: set-vm-max-map-count
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sysctl', '-w', 'vm.max_map_count=262144']
        securityContext:
          privileged: true
      - name: volume-mount-hack
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data /usr/share/elasticsearch/log"]
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
        - name: log
          mountPath: /usr/share/elasticsearch/log
      imagePullSecrets:
      - name: myregistrykey
      containers:
      - name: elasticsearch
        image: $REGISTRY_SERVER/docker/elasticsearch:6.3.2
        imagePullPolicy: imagePullPolicy
        securityContext:
          privileged: true
          capabilities:
            add:
            - IPC_LOCK
            - SYS_RESOURCE
        env:
        - name: ES_JAVA_OPTS
          value: "-Xms1g -Xmx1g"
        - name: ELASTIC_PASSWORD
          value: "$ELASTICSEARCH_PASSWORD"
        ports:
        - name: http
          containerPort: 9200
        - name: transport
          containerPort: 9300
        resources:
          requests:
            cpu: 1
            memory: 1000Mi
          limits:
            cpu: 2
            memory: 2000Mi
        volumeMounts:
        - name: config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
        - name: config
          mountPath: /usr/share/elasticsearch/config/log4j2.properties
          subPath: log4j2.properties
        - name: data
          mountPath: /usr/share/elasticsearch/data
        - name: log
          mountPath: /usr/share/elasticsearch/log
      volumes:
      - name: config
        configMap:
          name: elasticsearch
      - name: data
        hostPath:
          path: /data/efk/elasticsearch/data
      - name: log
        hostPath:
          path: /data/efk/elasticsearch/log
      #- name: datalog
      #  persistentVolumeClaim:
      #    claimName: elasticsearch

#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: elasticsearch
#  labels:
#    app: elasticsearch
#    stack: efk
#spec:
#  storageClassName: standard
#  accessModes:
#  - ReadWriteOnce
#  resources:
#    requests:
#      storage: 10G
