apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
    stack: efk
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: elasticsearch
        stack: efk
    spec:
      serviceAccountName: elasticsearch
      initContainers:
      - name: set-vm-max-map-count
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sysctl', '-w', 'vm.max_map_count=262144']
        securityContext:
          privileged: true
      - name: volume-mount-hack
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "chown -R 1000:100 /usr/share/elasticsearch/data"]
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: efknode
                operator: In
                values:
                - "true"
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.0.1
        imagePullPolicy: IfNotPresent
        env:
        - name: ES_JAVA_OPTS
          value: -Xms2g -Xmx2g
        - name: ES_JVM_HEAP
          value: 1024m
        - name: ES_MEM_LIMIT
          value: 2g
        - name: NETWORK_HOST
          value: elasticsearch-efk
        - name: MINIMUM_MASTER_NODES
          value: 1
        - name: UNICAST_HOSTS
          value: elasticsearch-efk.$NAMESPACE.svc:9300
        ports:
        - name: api
          containerPort: 9200
        - name: transport
          containerPort: 9300
        resources:
          limits:
            memory: "2147483648"
        volumeMounts:
        - name: config
          mountPath: /usr/share/elasticsearch/elasticsearch.yml
          subPath: elasticsearch.yml
        - name: datalog
          mountPath: /usr/share/elasticsearch
      # Allow non-root user to access PersistentVolume
      securityContext:
        fsGroup: 1000
      restartPolicy: Always
      volumes:
      - name: config
        configMap:
          name: elasticsearch
      - name: datalog
        hostPath:
          path: /data/efk/elasticsearch
      #- name: data
      #  persistentVolumeClaim:
      #    claimName: elasticsearch

#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: elasticsearch
#  labels:
#    app: elasticsearch
#    stack: efk
#spec:
#  storageClassName: standard
#  accessModes:
#  - ReadWriteOnce
#  resources:
#    requests:
#      storage: 1G
