apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-efk
  labels:
    app: elasticsearch
    stack: logging
spec:
  type: ClusterIP
  ports:
  - name: api
    port: 9200
    targetPort: 9200
  - name: transport
    port: 9300
    targetPort: 9300
  selector:
    app: elasticsearch
    stack: logging
