apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana
  labels:
    app: kibana
    stack: logging
data:
  kibana.yml: |
    server:
      name: Kibana
      host: 0.0.0.0
      port: 5601
    elasticsearch.url: "http://elasticsearch-efk.$NAMESPACE.svc:9200"
    elastalert.serverHost: elasticsearch-efk.$NAMESPACE.svc
    kibana.defaultAppId: "discover"
    logging.dest: stdout
    logging.quiet: true
