apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana
  labels:
    app: kibana
    stack: efk
data:
  kibana.yml: |
    server:
      name: $KIBANA_URL
      host: 0.0.0.0
      port: 5601
    elasticsearch:
      url: http://elasticsearch.$NAMESPACE.svc:9200
      username: $ELASTICSEARCH_USER
      password: $ELASTICSEARCH_PASSWORD
    logging:
      dest: stdout
      quiet: true
      useUTC: false
    # each of the xpack features should be enabled, or it will be unable to start otherwise
    xpack.ml.enabled: true
    xpack.graph.enabled: true
    xpack.watcher.enabled: true
    xpack.security.enabled: true
    xpack.reporting.enabled: true
    xpack.searchprofiler.enabled: true
    xpack.monitoring.enabled: true
    xpack.monitoring.ui.container.elasticsearch.enabled: true
