apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana
  labels:
    app: kibana
    stack: efk
data:
  kibana.yml: |
    server:
      name: Kibana
      host: localhost
      port: 5601
    elasticsearch:
      url: http://elasticsearch.$NAMESPACE.svc:9200
      username: elastic
      password: $ELASTICSEARCH_PASSWORD
    logging:
      dest: stdout
      quiet: true
      useUTC: false
    optimize.enabled: false
    kibana.defaultAppId: "discover"
    xpack.graph.enabled: true
    xpack.security.enabled: true
    xpack.searchprofiler.enabled: true
    xpack.monitoring.enabled: true
    xpack.ml.enabled: false
    xpack.reporting.enabled: false
    xpack.watcher.enabled: false
