apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kibana
  labels:
    app: kibana
    stack: efk
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kibana
        stack: efk
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: efknode
                operator: In
                values:
                - "true"
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana-oss:6.0.1
        imagePullPolicy: IfNotPresent
        env:
        - name: ELASTALERT_SERVERHOST
          value: "elasticsearch-efk.$NAMESPACE.svc"
        - name: ELASTICSEARCH_URL
          value: "http://elasticsearch-efk.$NAMESPACE.svc:9200"
        #- name: ELASTICSEARCH_USERNAME
        #  value: "user"
        #- name: ELASTICSEARCH_PASSWORD
        #  value: "password"
        ports:
        - containerPort: 5601
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: config
          mountPath: /usr/share/kibana/kibana.yml
          subPath: kibana.yml
      restartPolicy: Always
      volumes:
      - name: config
        configMap:
          name: kibana
