apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kibana
  labels:
    app: kibana
    stack: efk
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kibana
        stack: efk
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: efknode
                operator: In
                values:
                - "true"
      initContainers:
      - name: wait-for-es
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'sleep 10; until nslookup elasticsearch.$NAMESPACE.svc; do echo waiting for es; sleep 3; done;']
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:6.0.1
        imagePullPolicy: IfNotPresent
        env:
        - name: ELASTALERT_SERVERHOST
          value: "elasticsearch.$NAMESPACE.svc"
        - name: ELASTICSEARCH_URL
          value: "http://elasticsearch.$NAMESPACE.svc:9200"
        - name: KIBANA_PASSWORD
          value: "$KIBANA_PASSWORD"
        ports:
        - containerPort: 5601
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: config
          mountPath: /usr/share/kibana/kibana.yml
          subPath: kibana.yml
      restartPolicy: Always
      volumes:
      - name: config
        configMap:
          name: kibana
