apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kibana
  labels:
    app: kibana
    stack: efk
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kibana
        stack: efk
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: efknode
                operator: In
                values:
                - "true"
      initContainers:
      - name: wait-for-es
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "until nc -z elasticsearch.efk.svc 9200; do sleep 1; done;"]
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:6.3.1
        imagePullPolicy: IfNotPresent
        env:
        - name: KIBANA_PASSWORD
          value: "$KIBANA_PASSWORD"
        ports:
        - containerPort: 5601
        resources:
          requests:
            cpu: 0.5
            memory: 400Mi
          limits:
            cpu: 1
            memory: 800Mi
        volumeMounts:
        - name: config
          mountPath: /usr/share/kibana/config/kibana.yml
          subPath: kibana.yml
        - name: data
          mountPath: /usr/share/kibana/data
      restartPolicy: Always
      volumes:
      - name: config
        configMap:
          name: kibana
      - name: data
        hostPath:
          path: /data/efk/kibana/data
