apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kibana
  labels:
    app: kibana
    stack: logging
spec:
  rules:
  -
    # host: kibana.minikube.localnet
    host: kibana.j9egj.k8s.ginger.eu-central-1.aws.gigantic.io
    http:
      paths:
      - path: /
        backend:
          serviceName: kibana
          servicePort: 5601
