apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    app: kibana
    stack: efk
spec:
  type: ClusterIP
  ports:
  - name: ui
    port: 5601
    targetPort: 5601
  selector:
    app: kibana
    stack: efk
